### ISSUE TITLE
Clarify graph labels

### ISSUE THREAD

**Issue by d4weed** [Vizzuality/bbvatourism#2]
I t's not clear what the user is seeing when selecting for instance France / Food 

I'm assuming the map shows the results of an AND query, but what does the graph below show?
![image](https://cloud.githubusercontent.com/assets/1506306/7258477/318d39d6-e85d-11e4-906f-d619b7a45bc4.png)

Is it total, total FRANCE and total FRANCE AND FOOD?

If so then I think the legend should reflect it. If what the graph shows is what the legend reads (total for both France and food) would that be the same the map is showing?

**Comment by adammulligan** [comment]
You're right on both of those: the graph and the map would be showing the equivalent of "WHERE country = france AND category = food".

Maybe something like "Total Spending by France, Total Spending by France on Food"?
