### ISSUE TITLE
Parameterize zoomed areas and add top 5 by origin

### ISSUE THREAD

**Issue by d4weed** [Vizzuality/bbvatourism#3]
Instead of hardgoding the areas we can use the table pdata_zoom, where the_geom corresponds to the bounding box

Also, when showing the zoomed areas we need to also show the top 5 countries by spending in that area using this query

SELECT sum(amount) as amount, country FROM pdata, pdata_zoom where st_intersects(pdata.the_geom, pdata_zoom.the_geom) and pdata_zoom.cartodb_id=3
group by country
ORDER BY amount desc
LIMIT 5

@Adam, once you have the data displaying you can ask @eduardo to think of styling?

**Comment by adammulligan** [comment]
All right, I'll get on that now. @d4weed I'm going to cache pdata_zoom locally as JSON, unless you have plans to change it?

**Comment by d4weed** [comment]
Yeah, go ahead, we can always re-create the JSON if it changes

**Comment by d4weed** [comment]
I don't see the top five table. Was it added?

**Comment by adammulligan** [comment]
@d4weed yep, styled and deployed
