### ISSUE TITLE
Change country dashboard sparklines

### ISSUE THREAD

**Issue by d4weed** [Vizzuality/bbvatourism#5]
let's just leave 2 sparklines with amount and number of transactions aggregated by weekday.

Queries are

SELECT EXTRACT(DOW FROM  date) as dow,sum(amount) as total_amount FROM pdata Where country='PT'
GROUP BY dow
order by dow asc

SELECT EXTRACT(DOW FROM  date) as dow,count(cartodb_id) as total_amount FROM pdata Where country='PT'
GROUP BY dow
order by dow asc

dow returns values 0-6 where 0 is Sunday

**Comment by adammulligan** [comment]
@d4weed reduced down to two graphs. I've made the axes show <day>/<month> rather than <day> because evenly spacing the axis ticks will just result in something like "Sunday, Sunday, Sunday"

**Comment by d4weed** [comment]
Hey @adammulligan ,

The queries I wrote above should just return 7 rows, one per each day (with the aggregated count per each). The idea is to show how people spend during the week, no need to have the whole 2 months

**Comment by adammulligan** [comment]
Ahh I get you, I'll do that now

**Comment by adammulligan** [comment]
Sorry about that, deployed now with graphs by day of the week

**Comment by d4weed** [comment]
No problem :)

Can we chack how we are aligning the y axis anf maybe add a scale to it?

Things like this shouldn't happen:

![image](https://cloud.githubusercontent.com/assets/1506306/7494509/4d5a6984-f408-11e4-9bb4-7ead3e89c0e2.png)

**Comment by d4weed** [comment]
that's Venezuela, BTW

**Comment by adammulligan** [comment]
Yep, fixed. Let me think about the y scale, the numbers are pretty huge so we'll need to format them I think

**Comment by adammulligan** [comment]
How about this?

![screenshot 2015-05-06 15 18 22](https://cloud.githubusercontent.com/assets/182921/7495024/2da0bb48-f403-11e4-8e9f-29bfc4891ab9.png)

**Comment by d4weed** [comment]
if we can just have a min and a max I think it would be cleaner (don't even need vertical line, just two ticks bottom and top).

Is that zero line real, or just an example?

**Comment by d4weed** [comment]
BTW the number formatting is cool

**Comment by adammulligan** [comment]
Yeah, I think it is better without the whole scale. Zero line was real, but I've rescaled to have the min value as the base: 
![screenshot 2015-05-06 16 12 26](https://cloud.githubusercontent.com/assets/182921/7496231/d214c546-f40a-11e4-81e3-2bc10bdbb081.png)

**Comment by d4weed** [comment]
cool!

On Wed, May 6, 2015 at 5:13 PM, Adam Mulligan <notifications@github.com>
wrote:

> Yeah, I think it is better without the whole scale. Zero line was real,
> but I've rescaled to have the min value as the base:
> [image: screenshot 2015-05-06 16 12 26]
> <https://cloud.githubusercontent.com/assets/182921/7496231/d214c546-f40a-11e4-81e3-2bc10bdbb081.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vizzuality/bbvatourism/issues/5#issuecomment-99507048>
> .
>



-- 
David González
*Vizzuality*
C/. Eloy Gonzalo, 27 2º Puerta 7 - 28010 MADRID
M. +34 609125183
skype: david.gonzalez.camara
www.vizzuality.com

**Comment by adammulligan** [comment]
deployed all latest changes :+1:
