### ISSUE TITLE
Query functions

### ISSUE THREAD

**Issue by adammulligan** [Vizzuality/bbvatourism#7]
@d4weed as the named maps now seem to be working, here's a list of queries we use so you can put them in to functions:

## Bottom graph queries:

```
SELECT SUM(amount) as total_spent,
COUNT(*) transaction_count,
date_trunc('day', date::timestamp) as timestamp
FROM pdata
WHERE cat = <cat> AND country = <cat>
GROUP BY timestamp ORDER BY timestamp ASC

SELECT SUM(amount) as total_spent,
COUNT(*) transaction_count,
date_trunc('day', date::timestamp) as timestamp
FROM pdata
WHERE cat = <cat>
GROUP BY timestamp ORDER BY timestamp ASC

SELECT SUM(amount) as total_spent,
COUNT(*) transaction_count,
date_trunc('day', date::timestamp) as timestamp
FROM pdata
WHERE country = <cat>
GROUP BY timestamp ORDER BY timestamp ASC
```

## Country dashboard queries:

```
SELECT COUNT(DISTINCT key) as total_visitors,
SUM(amount) as total_spent,
COUNT(*) transaction_count
FROM pdata
WHERE country = <iso>

SELECT EXTRACT(DOW FROM date) as dow,
SUM(amount) as total_spent,
COUNT(cartodb_id) as transaction_count
FROM pdata
WHERE country = <iso>
GROUP BY dow
ORDER BY dow ASC

SELECT cat,
COUNT(*) transaction_count
FROM pdata
WHERE country = <iso>
GROUP BY cat
```

## Category dashboard queries

```
SELECT COUNT(DISTINCT key) as total_visitors,
SUM(amount) as total_spent,
COUNT(*) transaction_count
FROM pdata
WHERE cat = <cat>

SELECT EXTRACT(DOW FROM date) as dow,
SUM(amount) as total_spent,
COUNT(cartodb_id) as transaction_count
FROM pdata
WHERE cat = <cat>
GROUP BY dow
ORDER BY dow ASC

SELECT country,
COUNT(*) transaction_count
FROM pdata
WHERE cat = <cat>
GROUP BY country
```

## Tourist map query

```
SELECT count, country, total_amount,
ST_ConvexHull((the_geom_webmercator)) AS the_geom_webmercator
FROM pdata_areas
WHERE country = <iso>
```

**Comment by adammulligan** [comment]
@d4weed the function didn't have `country`, so I created a new function with it added: `get_all_2`. However because we're hiding the `key` attribute, we can't calculate the total unique visitors for the country stats. I suppose the only solution is to remove that stat, unless you're happy for the `key` to be exposed?

**Comment by d4weed** [comment]
I created a couple extra functions for the stats:

select * from get_stats_by_cat('es_barsandrestaurants')

select * from get_stats_by_country('PT')

regarding the function get_all_2() did you include the security definer?

On Fri, May 8, 2015 at 9:32 AM, Adam Mulligan <notifications@github.com>
wrote:

> @d4weed <https://github.com/d4weed> the function didn't have country, so
> I created a new function with it added: get_all_2. However because we're
> hiding the key attribute, we can't calculate the total unique visitors
> for the country stats. I suppose the only solution is to remove that stat,
> unless you're happy for the key to be exposed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vizzuality/bbvatourism/issues/7#issuecomment-100133030>
> .
>



-- 
David González
*Vizzuality*
C/. Eloy Gonzalo, 27 2º Puerta 7 - 28010 MADRID
M. +34 609125183
skype: david.gonzalez.camara
www.vizzuality.com

**Comment by adammulligan** [comment]
All queries now using the correct function: either get_all or the more specific ones you posted before.
