### ISSUE TITLE
Fix query when changing to "torist ravels"

### ISSUE THREAD

**Issue by d4weed** [Vizzuality/bbvatourism#8]
If I go to "provincial and choose China, then change to Tourist travels, the name "China" shows up but the tiles are for france.

Make sure the selected country on "Transactions" and "probincial" tabs gets passed correctly to "travels"

Also, when no county is selected and the user goes to "travels" let's make "Austria" the pre-selected default

**Comment by adammulligan** [comment]
Ah yep, fixed that and changed the default :+1:
